<a href="https://colab.research.google.com/github/rtrochepy/machine_learning/blob/main/Data_Classification_with_TorchText.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Neural Networks Course with PyTorch**

**Instructor:** Omar Uriel Espejel Diaz


**Tensors in PyTorch**

Tensors are a key component for creating and training machine learning models, allowing operations such as matrix multiplication and element-wise multiplication on large data sets. They are also useful for tasks like image processing, where you can represent an image as a three-dimensional tensor of pixels.

Tensors are super flexible and can be used for all kinds of data, not just images or numbers. You can use them for things like text data, where you can represent words as vectors or embeddings.

By mastering tensors, you'll be able to tackle more complex deep learning problems and develop more sophisticated models.

**Example of a layer with tensors**

This example of a PyTorch layer that uses tensors to create the key building block in modern artificial intelligence, the attention layer in Transformer models.

**Let's go step by step.**

**1.1 Creating Tensors**

**Import PyTorch.**


In [1]:
import torch

**Let's review the version of PyTorch we are using.**

In [2]:
print(torch.__version__)

2.0.1+cu118


Scalars, vectors, matrices, and tensors are mathematical concepts used in deep learning and other fields of science and engineering.

A scalar is a unique numerical value, such as **3** or **5.7**.

A vector is a one-dimensional array of numerical values, such as **[1, 2, 3]** or **[0.2, 0.5, 0.8]**.

A matrix is a two-dimensional array of numerical values, such as **[[1, 2, 3], [4, 5, 6], [7, 8, 9]]** or **[[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]]**.

A tensor is a multidimensional array of numerical values, which can be considered as a generalization of vectors and matrices.

A scalar is a tensor of order 0, a vector is a tensor of the first order, and a matrix is a tensor of the second order. Higher-order tensors, such as a third-order tensor or a fourth-order tensor, can represent more complex data structures, such as images or videos.

Here's a simple illustration:

Scalar: **3**
Vector: **[1, 2, 3]**
Matrix: **[[1, 2], [3, 4], [5, 6]]**
Tensor: **[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]**

We can represent these data structures with PyTorch. We can create tensors using different types of values. For example, random, zeros, or ones.

In [3]:
escalar = torch.randn(1)
vector = torch.zeros(1,10)
matriz = torch.ones(2,2)

matriz

tensor([[1., 1.],
        [1., 1.]])

But we can also represent structures with no common name:

In [4]:
t5 = torch.randn(5,2,3)

t5

tensor([[[-0.9547,  0.7273,  0.0539],
         [ 1.0332,  0.5827,  0.3404]],

        [[-0.2962,  0.0048,  0.5620],
         [-1.6079,  0.8106,  1.5160]],

        [[-0.5480, -1.2391,  0.4620],
         [ 0.9818,  0.5620, -1.8923]],

        [[-0.5486,  2.0911, -0.7131],
         [-3.1374, -0.4316,  0.8957]],

        [[ 0.4705,  1.5177,  1.2811],
         [ 0.6595,  0.5111, -0.3676]]])

We can create tensors with the values we want, not necessarily random ones.

In [5]:
torch.tensor([[2,2], [3,3]])

tensor([[2, 2],
        [3, 3]])

**Debugging operations with tensors**

When working with tensors, and the operations turn out to be invalid, we will have these three most common problems:

1. The size or shape.
2. The datatype.
3. The device on which the tensor is located.

The shape tells you how the elements within the tensor are organized.

In [6]:
print(f"La shape de la matriz es {matriz.shape}")
print(f"La shape de t5 es {t5.shape}")

La shape de la matriz es torch.Size([2, 2])
La shape de t5 es torch.Size([5, 2, 3])


We can also know the dimension of a tensor.

In [7]:
print(f"La shape de la matriz es {matriz.ndim}")
print(f"La shape de t5 es {t5.ndim}")

La shape de la matriz es 2
La shape de t5 es 3


Tensors can have elements with different types. It's important to know what type we are using.

The most common type is torch.float or torch.float32 (32-bit float). When we talk about bits, we are dealing with the size of the information needed to represent a number. In machine learning, we work with thousands of numbers, so choosing the ideal size is key.

**The rule is:** lower-bit data types (i.e., less precise) are faster to compute but sacrifice accuracy (faster to compute, but less accurate).

Normally, when we operate between tensors, PyTorch converts the tensors into compatible types, but it is important that we are aware of the type of the tensors to avoid future errors.

In [8]:
matriz_float32 = torch.tensor([[3.1,3.2], [3.3,3.4]])
matriz_uint64 = torch.tensor([[3,3], [3,3]])

# matriz_float32.dtype, matriz_uint64.dtype

(matriz_float32 + matriz_uint64).dtype

torch.float32

If necessary, we can use y = y.to(...) to convert tensors to different types.

In [9]:
matriz_uint64.to(torch.float32)

tensor([[3., 3.],
        [3., 3.]])

We must take into account the device for which our tensor is prepared. We cannot operate with a tensor designed for GPU (CUDA) and one for CPU.

In [10]:
matriz_uint64.device

device(type='cpu')

We check if we have a GPU available with **cuda.is_available()**.

CUDA is a parallel computing platform and an application programming interface (API) that allows us to leverage the power of GPUs for deep learning tasks. When we use CUDA, we can perform complex mathematical operations in parallel on the GPU, which can significantly accelerate the training and inference of machine learning models.

By using CUDA, we can take advantage of the massive parallel processing capabilities of GPUs and train models much faster than we could using only the CPU. Google Colab allows us to use a GPU at no cost.

In [11]:
torch.cuda.is_available()

False

In the following code, we will check if we have CUDA available and, if so, convert CPU tensors to CUDA and vice versa, while also changing the type.

It will return an error because we cannot operate with tensors on different devices.

In [12]:
if torch.cuda.is_available():
  matriz_uint64_cuda = matriz_uint64.to(torch.device("cuda"))

  print(matriz_uint64_cuda, matriz_uint64_cuda.type())
  print(matriz_uint64_cuda.to("cpu", torch.float32))

  # matriz_uint64_cuda + matriz_uint64

**1.2 Interaction with NumPy**

Convert the tensor to NumPy.

In [13]:
type(matriz.numpy())

numpy.ndarray

Import NumPy.

In [14]:
import numpy as np

Note that we can also convert from NumPy to PyTorch, and the type is maintained.

In [15]:
vector = np.ones(5)
torch.from_numpy(vector).dtype

torch.float64

**Operations with tensors**

First, let's create some tensors in PyTorch:

In [16]:
# create a tensor of zeros with shape (3, 4)
zeros_tensor = torch.zeros((3, 4))

# create a tensor of ones with shape (3, 4)
ones_tensor = torch.ones((3, 4))

# create a tensor of random values with shape (2, 2)
random_tensor = torch.randn((4))

In [17]:
random_tensor.shape

torch.Size([4])

Let's perform "element-wise" operations:

In [18]:
# add two tensors element-wise
added_tensor = zeros_tensor + ones_tensor

# subtract two tensors element-wise
subtracted_tensor = zeros_tensor - ones_tensor

# multiply two tensors element-wise
multiplied_tensor = zeros_tensor * ones_tensor

# divide two tensors element-wise
divided_tensor = random_tensor / ones_tensor

In [19]:
divided_tensor

tensor([[ 1.0549, -0.9265, -0.2616, -0.7132],
        [ 1.0549, -0.9265, -0.2616, -0.7132],
        [ 1.0549, -0.9265, -0.2616, -0.7132]])

Matrix multiplication:

In [20]:
# create two matrices
matrix1 = torch.randn(2,3)
matrix2 = torch.randn(3,2)

# print(f"matrix1 shape: {matrix1.shape}")
# print(f"matrix2 shape: {matrix2.shape}")

# perform matrix multiplication
torch.matmul(matrix1, matrix2).shape

torch.Size([2, 2])

These are just some examples of the types of operations you can perform on PyTorch tensors. You can also perform other operations such as taking the transpose of a tensor, changing the shape of a tensor, and more.

Always remember to pay attention to the shape and data types of your tensors when performing operations.

**Conclusion:**

The given text provides an in-depth understanding of tensors in PyTorch, how they are applied in machine learning models, and the various operations that can be performed with them. By mastering these foundational concepts, one can tackle complex deep learning problems and develop more advanced models. The translation covers a range of topics including tensor creation, debugging, interaction with NumPy, and specific operations. With practical examples and a clear focus on understanding the characteristics of tensors, this guide offers a valuable resource for anyone looking to delve into machine learning or deepen their understanding of PyTorch and its applications.